name: Build and Push Docker Images

on:
  push:
    branches:
      - main    # oder master, je nachdem welchen Hauptbranch Sie verwenden
    paths:
      - 'latest/**'
      - 'VERSION'
      - '.github/workflows/docker-build.yml'
  workflow_dispatch:  # Ermöglicht manuelle Ausführung

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Read WordPress version
        id: version
        run: |
          WP_VERSION=$(cat VERSION | tr -d '\r\n')
          echo "Version from file: $WP_VERSION"
          echo "WP_VERSION=$WP_VERSION" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./latest/php8.3/apache
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPOSITORY }}:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPOSITORY }}:${{ env.WP_VERSION }}-php8.3-apache
          cache-from: type=gha
          cache-to: type=gha,mode=max